name: Generate Paarungen

on:
  push:
    branches:
      - main

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # Setzen Sie hier Ihre Go-Version ein

      - name: Build and Run Go Program
        run: |
          go get ./...
          go build -o och_nee_fussball .
          ./och_nee_fussball

      - name: Commit and Push Paarungen.txt
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b paarungen
          git add paarungen.txt
          git commit -m "Adds Paarungen.txt"
          git push origin paarungen
